version: '3.7'

services:

  api:
    container_name: slc-api
    build:
      context: ./api
      dockerfile: ./api/Dockerfile
    env_file:
        - ./api/.env
        - ./api/.env.development
    volumes:
      - './api:/app'
      - '/app/node_modules'
    ports:
      - 3050:3050
    environment:
      - CHOKIDAR_USEPOLLING=true
  web:
    container_name: slc-web
    build:
      context: ./web
    env_file:
      - ./web/.env
      - ./web/.env.development
    environment:
      # NOTE: the below var allows reloading
      - CHOKIDAR_USEPOLLING=true
# TODO: add image info that uses env vals
#    image: 'slc-web:${SLC_WEB_DOCKER_TAG}'
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
