version: '3.7'

services:

  api:
    container_name: slc-api
    build:
      context: ./api
      dockerfile: ./api/Dockerfile
    volumes:
      - './api:/app'
      - '/app/node_modules'
    ports:
      - 3050:3050
    environment:
      - CHOKIDAR_USEPOLLING=true
  web:
    container_name: slc-web
    build:
      context: ./web
      dockerfile: ./web/Dockerfile
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
