version: '3.7'

services:

  web:
    container_name: slc-web
    build:
      context: ./web
      dockerfile: ./web/Dockerfile
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
